# -*- coding: utf-8 -*-
"""engage-algo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vuBWg8fSprvJK19BzxCpTX2chKEMQ88X
"""

import numpy as np
import pandas as pd

movies = pd.read_csv('tmdb_5000_movies.csv') 
credits = pd.read_csv('tmdb_5000_credits.csv')

movies.head(1)

credits.head(1)

movies = movies.merge(credits,on='title')

movies.shape

credits.shape

movies.head(1)

movies = movies[['movie_id', 'title', 'overview','genres', 'keywords', 'cast', 'crew' ]]

movies.head()

movies.isnull().sum()

movies.dropna(inplace=True)

movies.isnull().sum()

movies.duplicated().sum()

movies.iloc[0].genres

import ast
ast.literal_eval

def convert(obj):
  L = []
  for i in ast.literal_eval(obj):
    L.append(i['name'])
    return L

movies['genres'] = movies['genres'].apply(convert)

movies['cast']

movies['keywords'] = movies['keywords'].apply(convert)

def convert3(obj):
  L = []
  counter = 0 
  for i in ast.literal_eval(obj):
      if counter != 3: 
         L.append(i['name'])
         counter+=1
      else : 
          break
      return L

movies['cast'] = movies['cast'].apply (convert3)

movies.head()

def fetch_director(obj):
  L = []
  for i in ast.literal_eval(obj):
    if i['job'] == 'Director':
     L.append(i['name'])
     break
  return L

movies['crew'].apply(fetch_director)

movies['overview'] = movies['overview'].apply(lambda x:x.split())

def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

movies.sample(5)

